### ISSUE TITLE
Not  Issue But question

### ISSUE THREAD

**Issue by Therealjosephchrzempiec** [svenpetersen1965/C64-WiFi-Modem-User-Port#1]
Hello i wonder if this will work on the Commodore Vic 20 as well? I have one but not a Commodore  64?

Joseph

**Comment by svenpetersen1965** [comment]
Sorry for the late reply. I don't know, if it work on a VIC-20, since it requires a certain terminal software and I actually don't know, if there is one like that for the VIC-20. My VIC-20 is not working, so I can't try it out.

**Comment by svenpetersen1965** [comment]
Meanwhile, I have tried out this C64 wifi modem on a VIC-20 with a VICTerm 4.0 (cartridge). It works well.
